# Generated by Django 3.1.7 on 2021-03-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninstance',
            name='increment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
