# Generated by Django 3.1.7 on 2021-03-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_requests',
            field=models.IntegerField(default=0),
        ),
    ]
