# Generated by Django 3.1.7 on 2021-03-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0004_profile_num_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='num_requests',
            new_name='num_get_requests',
        ),
        migrations.AddField(
            model_name='profile',
            name='num_post_requests',
            field=models.IntegerField(default=0),
        ),
    ]
