# Generated by Django 3.1.7 on 2021-03-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0005_auto_20210314_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apikey',
        ),
        migrations.AddField(
            model_name='profile',
            name='get_api_key',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_api_key',
            field=models.CharField(default='', max_length=512),
        ),
    ]
