# Generated by Django 3.1.7 on 2021-03-14 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0007_auto_20210314_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='event_context',
            new_name='code_context',
        ),
    ]
