# Generated by Django 3.1.7 on 2021-03-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0008_auto_20210314_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_update_delete_api_key',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='profile',
            name='read_api_key',
            field=models.CharField(default='', max_length=512),
        ),
    ]
