# Generated by Django 3.1.7 on 2021-03-22 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0009_auto_20210318_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='create_update_delete_api_key',
            new_name='cud_api_key',
        ),
    ]
