# Generated by Django 3.1.7 on 2021-03-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0010_auto_20210322_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='get_api_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='num_get_requests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='num_post_requests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_api_key',
        ),
    ]
