# Generated by Django 3.1.7 on 2021-04-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0011_auto_20210322_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject_rea',
            field=models.CharField(default='', max_length=50),
        ),
    ]
