# Generated by Django 3.1.7 on 2021-04-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0012_question_subject_rea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject_rea',
            new_name='subject_area',
        ),
    ]
