# Generated by Django 3.1.7 on 2021-04-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0015_auto_20210407_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_user',
            name='user',
        ),
    ]
