# Generated by Django 3.1.7 on 2021-04-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0016_remove_question_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question_User',
        ),
    ]
