# Generated by Django 3.1.7 on 2021-04-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0017_delete_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment', models.IntegerField(default=1)),
                ('remaining', models.IntegerField(default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpsrv.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpsrv.question')),
            ],
        ),
    ]
