# Generated by Django 3.1.7 on 2021-04-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0018_question_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_User',
            new_name='Question_Profile',
        ),
    ]
