# Generated by Django 3.1.7 on 2021-04-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0019_auto_20210407_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpsrv.profile')),
                ('questions', models.ManyToManyField(to='httpsrv.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_answer', models.IntegerField()),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('submitted_answer', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('question_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpsrv.question')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_timestamp', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpsrv.course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpsrv.profile')),
            ],
        ),
    ]
