# Generated by Django 3.1.7 on 2021-04-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0020_course_coursesubscriptions_questioninstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.TextField(default=''),
        ),
    ]
