# Generated by Django 3.1.7 on 2021-04-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0021_course_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
